### ISSUE TITLE
Native extension fails to build on OS X Mavericks

### ISSUE THREAD

**Issue by mmmmmrob** [rdp/google_hash#24]
I started taking a look at google_hash earlier on OS X Mavericks (10.9) and found a couple of issues.

First build failure I come across is

"dense_double_to_double.cpp:2:10: fatal error: 'google/dense_hash_map' file not found"

This was fixed by doing a 'brew install google-sparsehash' though I don't know if that was a good idea as I think that's installed a newer version than google_hash would build itself. That clears the issue above anyway.

The problem then becomes

"dense_double_to_double.cpp:4:10: fatal error: 'tr1/functional' file not found"

This appears to be an issue with C++ versions and the XCode 5 compiler (from a cursory google of the error).

Happy to provide full gem output and help with debugging.

rob

**Comment by rdp** [comment]
hopefully fixed now [at least builds in 10.10 for me...]
